name       : haskell-pcap
version    : 0.4.5.2
release    : 4
source     :
    - https://hackage.haskell.org/package/pcap-0.4.5.2/pcap-0.4.5.2.tar.gz : e7e92e6ff4bffa22102335a38dabb97fd0771fdf3b75d45cd7c1708c85e1cd5f
license    : BSD-3-Clause
component  : programming.haskell
summary    : A system-independent interface for user-level packet capture
description: |
    A system-independent interface for user-level packet capture
builddeps  :
    - haskell-cabal-install
    - haskell-network-devel
    - libpcap-devel
rundeps    :
    - devel:
        - haskell-network-devel
        - libpcap-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

